service: c5-soon-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment

functions:
  firstfunction:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /get666
          method: get
      # - sqs:
      #    arn: arn:aws:sqs:us-east-1:255945442255:delfrinando-pranata

  secondfunction:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /post888
          method: post

plugins:
  - serverless-offline